services:
db:
  image: postgres:14.3
  restart: always
  port:
    - "5432:5432"
  environment:
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
  container_name: teslodb
  volumes:
    - ./db:/var/lib/postgresql/data